/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chartadvisor.view;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Cristo
 */
public class DictionaryView extends javax.swing.JFrame {

    /**
     * Creates new form DictionaryView
     */
    public DictionaryView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/chartadvisor/view/images/mainicon.png"))).getImage());// ADD!!
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_Main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtxt_label = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtn_add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcbox_DataType = new javax.swing.JComboBox();
        jcbox_LOM = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_dictionary = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chart Advisor - Dictionary");
        setResizable(false);

        jpnl_Main.setBackground(new java.awt.Color(244, 244, 244));
        jpnl_Main.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setLayout(null);

        jtxt_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxt_label.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxt_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_labelActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_label);
        jtxt_label.setBounds(70, 50, 150, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("LOM:");
        jLabel1.setToolTipText("Level of Measurement");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 150, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Type:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 100, 50, 30);

        jbtn_add.setText("Add Value");
        jPanel1.add(jbtn_add);
        jbtn_add.setBounds(40, 200, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Label:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 50, 50, 30);

        jcbox_DataType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbox_DataType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Integer", "Float", "String" }));
        jPanel1.add(jcbox_DataType);
        jcbox_DataType.setBounds(70, 100, 150, 30);

        jcbox_LOM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbox_LOM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categorical", "Ordinal", "Quantitative" }));
        jPanel1.add(jcbox_LOM);
        jcbox_LOM.setBounds(70, 150, 150, 30);

        jpnl_Main.add(jPanel1);
        jPanel1.setBounds(10, 10, 230, 250);

        jPanel3.setBackground(new java.awt.Color(244, 244, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Available Elements", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel3.setLayout(null);

        jScrollPane2.setViewportView(jlist_dictionary);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 290, 190);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Label / Data Type / Level of Measurement");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 20, 300, 30);

        jpnl_Main.add(jPanel3);
        jPanel3.setBounds(250, 10, 310, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnl_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_labelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_add;
    private javax.swing.JComboBox jcbox_DataType;
    private javax.swing.JComboBox jcbox_LOM;
    private javax.swing.JList jlist_dictionary;
    private javax.swing.JPanel jpnl_Main;
    private javax.swing.JTextField jtxt_label;
    // End of variables declaration//GEN-END:variables

    public JButton getJbtn_add() {
        return jbtn_add;
    }

    public void setJbtn_add(JButton jbtn_add) {
        this.jbtn_add = jbtn_add;
    }

    public JList getJlist_dictionary() {
        return jlist_dictionary;
    }

    public void setJlist_dictionary(JList jlist_dictionary) {
        this.jlist_dictionary = jlist_dictionary;
    }

    public JPanel getJpnl_Main() {
        return jpnl_Main;
    }

    public void setJpnl_Main(JPanel jpnl_Main) {
        this.jpnl_Main = jpnl_Main;
    }

    public JTextField getJtxt_label() {
        return jtxt_label;
    }

    public void setJtxt_label(JTextField jtxt_label) {
        this.jtxt_label = jtxt_label;
    }

    public JComboBox getJcbox_DataType() {
        return jcbox_DataType;
    }

    public void setJcbox_DataType(JComboBox jcbox_DataType) {
        this.jcbox_DataType = jcbox_DataType;
    }

    public JComboBox getJcbox_LOM() {
        return jcbox_LOM;
    }

    public void setJcbox_LOM(JComboBox jcbox_LOM) {
        this.jcbox_LOM = jcbox_LOM;
    }
    
}
