/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chartadvisor.view;

import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Cristo
 */
public class MainView extends javax.swing.JFrame {
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(null);
        initCheckboxList(); // ADD!!
        this.setIconImage(new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/chartadvisor/view/images/mainicon.png"))).getImage());// ADD!!
    }
    
    // ADD!! CHECKBOX LIST ----------------------------------------------------------------------------------
    private ArrayList<CheckListItem> checkboxList = new ArrayList<CheckListItem>();
    private JScrollPane jscroll_properties;    
    public void initCheckboxList() {
        JList checkList = new JList(checkboxList.toArray());
        checkList.setCellRenderer(new CheckListRenderer());
        checkList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        checkList.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent event) {
                JList list = (JList) event.getSource();
                // Get index of item clicked
                int index = list.locationToIndex(event.getPoint());
                CheckListItem item = (CheckListItem)
                list.getModel().getElementAt(index);
                // Toggle selected state
                item.setSelected(! item.isSelected());
                // Repaint cell
                list.repaint(list.getCellBounds(index, index));
            }
        });
        jscroll_properties = new JScrollPane(checkList);
        jscroll_properties.setBounds(15, 30, 250, 250);
        this.getJpnl_PropertiesSelection().add(jscroll_properties);
    }
    
    public void setCheckBoxList(String[] lista) {
        checkboxList.clear();
        for(String item : lista) {
        	this.checkboxList.add(new CheckListItem(item));
        }
        getJpnl_PropertiesSelection().remove(jscroll_properties);
        initCheckboxList();
        jscroll_properties.revalidate();
        jscroll_properties.repaint();
    }
    
    public ArrayList<String> getCheckedItems() {
        ArrayList<String> selectedItems = new ArrayList<String>();
        for(CheckListItem oneItem : checkboxList) {
            if (oneItem.isSelected()) {
                selectedItems.add(oneItem.getLabel());
                System.out.println(oneItem.getLabel());
            }
        }
        return selectedItems;
    }

    public ArrayList<CheckListItem> getCheckboxList() {
		return checkboxList;
	}

	public void setCheckboxList(ArrayList<CheckListItem> checkboxList) {
		this.checkboxList = checkboxList;
	}

	public JScrollPane getJscroll_properties() {
		return jscroll_properties;
	}

	public void setJscroll_properties(JScrollPane jscroll_properties) {
		this.jscroll_properties = jscroll_properties;
	}
    // END!! -------------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_Banner = new javax.swing.JLabel();
        jpnl_Main = new javax.swing.JPanel();
        jtxt_FilePath = new javax.swing.JTextField();
        jbtn_Open = new javax.swing.JButton();
        jpnl_PropertiesSelection = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jradio_TXT = new javax.swing.JRadioButton();
        jradio_RDF = new javax.swing.JRadioButton();
        jradio_XML = new javax.swing.JRadioButton();
        jbtn_Cancel = new javax.swing.JButton();
        jbtn_Generate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenu_Open = new javax.swing.JMenuItem();
        jmenu_Generate = new javax.swing.JMenuItem();
        jmenu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenu_Dictionary = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmenu_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChartAdvisor - Semantic Web Project");
        setBackground(new java.awt.Color(241, 251, 255));
        setResizable(false);

        jlbl_Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/view_banner.png"))); // NOI18N

        jpnl_Main.setBackground(new java.awt.Color(244, 244, 244));
        jpnl_Main.setLayout(null);

        jtxt_FilePath.setEditable(false);
        jtxt_FilePath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxt_FilePath.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxt_FilePath.setText("...dataset.rdf");
        jpnl_Main.add(jtxt_FilePath);
        jtxt_FilePath.setBounds(120, 20, 450, 30);

        jbtn_Open.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/open.png"))); // NOI18N
        jbtn_Open.setText("Open");
        jpnl_Main.add(jbtn_Open);
        jbtn_Open.setBounds(30, 20, 90, 30);

        jpnl_PropertiesSelection.setBackground(new java.awt.Color(244, 244, 244));
        jpnl_PropertiesSelection.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Select Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jpnl_PropertiesSelection.setLayout(null);
        jpnl_Main.add(jpnl_PropertiesSelection);
        jpnl_PropertiesSelection.setBounds(30, 70, 280, 290);

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Output File", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setLayout(null);

        jradio_TXT.setBackground(new java.awt.Color(244, 244, 244));
        jradio_TXT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jradio_TXT.setForeground(new java.awt.Color(102, 102, 102));
        jradio_TXT.setText(".TXT");
        jradio_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradio_TXTActionPerformed(evt);
            }
        });
        jPanel2.add(jradio_TXT);
        jradio_TXT.setBounds(70, 100, 100, 23);

        jradio_RDF.setBackground(new java.awt.Color(244, 244, 244));
        jradio_RDF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jradio_RDF.setForeground(new java.awt.Color(102, 102, 102));
        jradio_RDF.setSelected(true);
        jradio_RDF.setText(".RDF");
        jradio_RDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradio_RDFActionPerformed(evt);
            }
        });
        jPanel2.add(jradio_RDF);
        jradio_RDF.setBounds(70, 40, 100, 23);

        jradio_XML.setBackground(new java.awt.Color(244, 244, 244));
        jradio_XML.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jradio_XML.setForeground(new java.awt.Color(102, 102, 102));
        jradio_XML.setText(".XML");
        jradio_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradio_XMLActionPerformed(evt);
            }
        });
        jPanel2.add(jradio_XML);
        jradio_XML.setBounds(70, 70, 100, 23);

        jpnl_Main.add(jPanel2);
        jPanel2.setBounds(360, 70, 210, 160);

        jbtn_Cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/cancel.png"))); // NOI18N
        jbtn_Cancel.setText("Cancel");
        jpnl_Main.add(jbtn_Cancel);
        jbtn_Cancel.setBounds(400, 310, 130, 30);

        jbtn_Generate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtn_Generate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/generate.png"))); // NOI18N
        jbtn_Generate.setText("Generate");
        jpnl_Main.add(jbtn_Generate);
        jbtn_Generate.setBounds(400, 260, 130, 30);

        jMenu1.setText("File");

        jmenu_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/open.png"))); // NOI18N
        jmenu_Open.setText("Open");
        jMenu1.add(jmenu_Open);

        jmenu_Generate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/generate.png"))); // NOI18N
        jmenu_Generate.setText("Generate");
        jMenu1.add(jmenu_Generate);

        jmenu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/cancel.png"))); // NOI18N
        jmenu_Exit.setText("Exit");
        jMenu1.add(jmenu_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");

        jmenu_Dictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/dictionary.png"))); // NOI18N
        jmenu_Dictionary.setText("Dictionary");
        jMenu2.add(jmenu_Dictionary);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jmenu_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chartadvisor/view/images/chart.png"))); // NOI18N
        jmenu_About.setText("Chart Advisor");
        jMenu3.add(jmenu_About);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbl_Banner)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jpnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbl_Banner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jradio_RDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradio_RDFActionPerformed
        if (this.jradio_RDF.isSelected()) {
            this.jradio_XML.setSelected(false);
            this.jradio_TXT.setSelected(false);
        } else {
            this.jradio_RDF.setSelected(true);
        }
    }//GEN-LAST:event_jradio_RDFActionPerformed

    private void jradio_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradio_XMLActionPerformed
        if (this.jradio_XML.isSelected()) {
            this.jradio_RDF.setSelected(false);
            this.jradio_TXT.setSelected(false);
        } else {
            this.jradio_XML.setSelected(true);
        }
    }//GEN-LAST:event_jradio_XMLActionPerformed

    private void jradio_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradio_TXTActionPerformed
        if (this.jradio_TXT.isSelected()) {
            this.jradio_RDF.setSelected(false);
            this.jradio_XML.setSelected(false);
        } else {
            this.jradio_TXT.setSelected(true);
        }
    }//GEN-LAST:event_jradio_TXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_Cancel;
    private javax.swing.JButton jbtn_Generate;
    private javax.swing.JButton jbtn_Open;
    private javax.swing.JLabel jlbl_Banner;
    private javax.swing.JMenuItem jmenu_About;
    private javax.swing.JMenuItem jmenu_Dictionary;
    private javax.swing.JMenuItem jmenu_Exit;
    private javax.swing.JMenuItem jmenu_Generate;
    private javax.swing.JMenuItem jmenu_Open;
    private javax.swing.JPanel jpnl_Main;
    private javax.swing.JPanel jpnl_PropertiesSelection;
    private javax.swing.JRadioButton jradio_RDF;
    private javax.swing.JRadioButton jradio_TXT;
    private javax.swing.JRadioButton jradio_XML;
    private javax.swing.JTextField jtxt_FilePath;
    // End of variables declaration//GEN-END:variables

    public JButton getJbtn_Cancel() {
        return jbtn_Cancel;
    }

    public void setJbtn_Cancel(JButton jbtn_Cancel) {
        this.jbtn_Cancel = jbtn_Cancel;
    }

    public JButton getJbtn_Generate() {
        return jbtn_Generate;
    }

    public void setJbtn_Generate(JButton jbtn_Generate) {
        this.jbtn_Generate = jbtn_Generate;
    }

    public JButton getJbtn_Open() {
        return jbtn_Open;
    }

    public void setJbtn_Open(JButton jbtn_Open) {
        this.jbtn_Open = jbtn_Open;
    }

    public JLabel getJlbl_Banner() {
        return jlbl_Banner;
    }

    public void setJlbl_Banner(JLabel jlbl_Banner) {
        this.jlbl_Banner = jlbl_Banner;
    }

    public JMenuItem getJmenu_About() {
        return jmenu_About;
    }

    public void setJmenu_About(JMenuItem jmenu_About) {
        this.jmenu_About = jmenu_About;
    }

    public JMenuItem getJmenu_Dictionary() {
        return jmenu_Dictionary;
    }

    public void setJmenu_Dictionary(JMenuItem jmenu_Dictionary) {
        this.jmenu_Dictionary = jmenu_Dictionary;
    }

    public JMenuItem getJmenu_Exit() {
        return jmenu_Exit;
    }

    public void setJmenu_Exit(JMenuItem jmenu_Exit) {
        this.jmenu_Exit = jmenu_Exit;
    }

    public JMenuItem getJmenu_Generate() {
        return jmenu_Generate;
    }

    public void setJmenu_Generate(JMenuItem jmenu_Generate) {
        this.jmenu_Generate = jmenu_Generate;
    }

    public JMenuItem getJmenu_Open() {
        return jmenu_Open;
    }

    public void setJmenu_Open(JMenuItem jmenu_Open) {
        this.jmenu_Open = jmenu_Open;
    }

    public JPanel getJpnl_Main() {
        return jpnl_Main;
    }

    public void setJpnl_Main(JPanel jpnl_Main) {
        this.jpnl_Main = jpnl_Main;
    }

    public JPanel getJpnl_PropertiesSelection() {
        return jpnl_PropertiesSelection;
    }

    public void setJpnl_PropertiesSelection(JPanel jpnl_PropertiesSelection) {
        this.jpnl_PropertiesSelection = jpnl_PropertiesSelection;
    }

    public JRadioButton getJradio_RDF() {
        return jradio_RDF;
    }

    public void setJradio_RDF(JRadioButton jradio_RDF) {
        this.jradio_RDF = jradio_RDF;
    }

    public JRadioButton getJradio_TXT() {
        return jradio_TXT;
    }

    public void setJradio_TXT(JRadioButton jradio_TXT) {
        this.jradio_TXT = jradio_TXT;
    }

    public JRadioButton getJradio_XML() {
        return jradio_XML;
    }

    public void setJradio_XML(JRadioButton jradio_XML) {
        this.jradio_XML = jradio_XML;
    }

    public JTextField getJtxt_FilePath() {
        return jtxt_FilePath;
    }

    public void setJtxt_FilePath(JTextField jtxt_FilePath) {
        this.jtxt_FilePath = jtxt_FilePath;
    }

    
}
